#!/bin/sh

vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -1)
mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')

# remove % sign for comparison
vol_num=$(echo "$vol" | tr -d '%')

if [ "$mute" = "yes" ]; then
    icon="󰝟"
elif [ "$vol_num" -ge 70 ]; then
    icon=" "
elif [ "$vol_num" -ge 30 ]; then
    icon=" "
else
    icon=" "
fi

printf "%s %s" "$icon" "$vol"
